### PR TITLE
Fixes 93 - Fixing issues with unstable homedir selection behavior on initial run…

### PR DESCRIPTION
**Pull request by tevert**
…. No actual Windows 10 issues found.

### CODE REVIEW

**Comment by shankera** [comment]
I approve of the code, but am not capable of merging, as I can not run the code to verify that it works on win10

**Comment by tevert** [comment]
There's nothing there that's Win10 specific. It's just the behavior of a clean install.

**Comment by shankera** [comment]
I see. I can verify this, then. one moment

**Comment by shankera** [comment]
Exception when I try to set /Music/ as my library directory 

System.IO.IOException: {"Access to the path 'Music' is denied."}
   at System.IO.DirectoryInfo.MoveTo(String destDirName)
   at MSOE.MediaComplete.Lib.Library.DataSource.FileSystem.<>c__DisplayClassb.<MoveDirectory>b__9(DirectoryInfo x) in t:\Programming\MediaComplete\MSOE.MediaComplete.Lib\Library\DataSource\FileSystem.cs:line 173
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at MSOE.MediaComplete.Lib.Library.DataSource.FileSystem.MoveDirectory(DirectoryPath oldPath, DirectoryPath newPath) in t:\Programming\MediaComplete\MSOE.MediaComplete.Lib\Library\DataSource\FileSystem.cs:line 173
   at MSOE.MediaComplete.Settings.BtnSelectHomeFolder_Click(Object sender, RoutedEventArgs e) in t:\Programming\MediaComplete\MSOE.MediaComplete\Settings.xaml.cs:line 104
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()

**Comment by tevert** [comment]
I can't seem to reproduce that locally - can you replicate it and debug it a bit? One interesting thing I notice is that that IOException should be giving the full file path in the message, so it looks like you're trying to move to an absolute path of "Music", which won't exist (or will be C:\Music at best).

**Comment by shankera** [comment]
Everything seems to be fine

**Pull request merged**
